version: '3.9'
name: 'sag'

networks:
  dev:

x-base-api: &base-project
  env_file:
    - .env
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ./:/opt/app

services:
  project:
    <<: *base-project
    command: ["make", "run"]
    depends_on:
      - postgres-db
    ports:
      - ${SERVER_PORT:-8000}:8000
    volumes:
      - ./:/opt/app
      - static_volume:/opt/app/static
    networks:
      - dev

  postgres-db:
    env_file:
      - .env
    image: postgres:15.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
    networks:
      - dev

volumes:
  static_volume:
  pg_data:
