# Generated by Django 5.2.3 on 2025-07-13 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('image', models.ImageField(blank=True, upload_to='carpet/', verbose_name='image')),
                ('collection_type', models.IntegerField(choices=[(1, '---'), (2, 'New'), (3, 'Sale'), (4, 'Hit')], default=0, verbose_name='collection_type')),
            ],
            options={
                'verbose_name': 'Carpet',
                'verbose_name_plural': 'Carpet',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('name_uz', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('name_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('image', models.ImageField(blank=True, upload_to='catalog_img/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Catalog',
                'verbose_name_plural': 'Catalog',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('name_uz', models.CharField(max_length=300, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=300, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=300, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Character',
            },
        ),
        migrations.CreateModel(
            name='CharacterTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='title')),
                ('title_uz', models.CharField(blank=True, max_length=250, null=True, verbose_name='title')),
                ('title_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='title')),
                ('title_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Character Title',
                'verbose_name_plural': 'Character Title',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('name_uz', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('name_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Color',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('from_price', models.IntegerField(default=0, verbose_name='from_price')),
                ('to_price', models.IntegerField(default=0, verbose_name='to_price')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Price',
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('name_uz', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('name_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Shape',
                'verbose_name_plural': 'Shape',
            },
        ),
        migrations.CreateModel(
            name='CarpetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('price', models.FloatField(default=0, verbose_name='price')),
                ('discount', models.FloatField(default=0, verbose_name='discount')),
                ('image', models.ImageField(blank=True, upload_to='carpet_model/', verbose_name='image')),
                ('collection_type', models.IntegerField(choices=[(1, '---'), (2, 'New'), (3, 'Sale'), (4, 'Hit')], default=0, verbose_name='collection_type')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.carpet', verbose_name='model')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='room')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalog', verbose_name='catalog')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.color', verbose_name='color')),
            ],
            options={
                'verbose_name': 'Carpet Model',
                'verbose_name_plural': 'Carpet Model',
            },
        ),
        migrations.CreateModel(
            name='CarpetModelImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('image', models.ImageField(blank=True, null=True, upload_to='carpet_model_images/', verbose_name='image')),
                ('carpet_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.carpetmodel', verbose_name='carpet_model')),
            ],
            options={
                'verbose_name': 'Carpet Model Images',
                'verbose_name_plural': 'Carpet Model Images',
            },
        ),
        migrations.AddField(
            model_name='carpet',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalog', verbose_name='catalog'),
        ),
        migrations.CreateModel(
            name='CharacterDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('detail', models.CharField(max_length=250, verbose_name='detail')),
                ('detail_uz', models.CharField(max_length=250, null=True, verbose_name='detail')),
                ('detail_ru', models.CharField(max_length=250, null=True, verbose_name='detail')),
                ('detail_en', models.CharField(max_length=250, null=True, verbose_name='detail')),
                ('character', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.character', verbose_name='character')),
                ('model', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.carpetmodel', verbose_name='model')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.charactertitle', verbose_name='title')),
            ],
            options={
                'verbose_name': 'Character Detail',
                'verbose_name_plural': 'Character Detail',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('width', models.IntegerField(default=0, verbose_name='width')),
                ('length', models.IntegerField(default=0, verbose_name='length')),
                ('price', models.FloatField(default=0, verbose_name='price')),
                ('discount', models.FloatField(default=0, verbose_name='discount')),
                ('carpet_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.carpetmodel', verbose_name='carpet_model')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.shape', verbose_name='shape')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Size',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('name_uz', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('name_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='name')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='catalog.catalog', verbose_name='catalog')),
            ],
            options={
                'verbose_name': 'Style',
                'verbose_name_plural': 'Style',
            },
        ),
        migrations.AddField(
            model_name='carpetmodel',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.style', verbose_name='style'),
        ),
    ]
