# Generated by Django 5.2.3 on 2025-07-13 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_characterdetail_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterdetail',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.charactertitle', verbose_name='title'),
        ),
    ]
