# Generated by Django 5.2.3 on 2025-07-13 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_characterdetail_title_delete_charactertitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='title')),
                ('title_uz', models.CharField(blank=True, max_length=250, null=True, verbose_name='title')),
                ('title_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='title')),
                ('title_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Character Title',
                'verbose_name_plural': 'Character Title',
            },
        ),
        migrations.AddField(
            model_name='characterdetail',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.charactertitle', verbose_name='title'),
        ),
    ]
