name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/sag/
            git pull
            
            echo "Cleanup docker (if necessary)..."
            docker system prune -af --volumes || true
            
            echo "Restarting Docker..."
            sudo systemctl restart docker || true
            
            echo "Docker Compose Down..."
            docker compose down || true
            
            echo "Docker Compose Up with Build..."
            docker compose up -d --build
                      
            echo "Apply migrations..."
            docker compose exec project python manage.py makemigrations --noinput || true
            docker compose exec project python manage.py migrate --noinput || true
